language: python
python:
  - 3.5.6
  - 3.6.4
  - 3.7.8
script:
  - JARDIN_CONF=/home/travis/build/instacart/jardin/tests/jardin_conf_pg.py python setup.py test
  - JARDIN_CONF=/home/travis/build/instacart/jardin/tests/jardin_conf_mysql.py python setup.py test
  - JARDIN_CONF=/home/travis/build/instacart/jardin/tests/jardin_conf_sqlite.py python setup.py test
  - JARDIN_CONF=/home/travis/build/instacart/jardin/tests/jardin_conf_pg_with_connection_pool.py python setup.py test
services:
  - postgresql
  - mysql
before_script:
  - psql --version
  - psql -c 'create database jardin_test;' -U postgres
  - mysql -e 'CREATE DATABASE jardin_test;'
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
    - PGPORT=5432
